package com.hros.vaadin;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

@Component
@Scope("session")
public class MainWindow extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel;
	@AutoGenerated
	private RightMainClosableTabSheet rightMainClosableTabSheet;
	@AutoGenerated
	private LeftMainLayout leftMainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_top;
	@AutoGenerated
	private Button button_logout;
	@AutoGenerated
	private Label label_curren_user;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainWindow() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		button_logout.addListener(new Button.ClickListener(){

			@Override
			public void buttonClick(ClickEvent event) {
				getWindow().getApplication().close();
			}});
		button_logout.setStyleName("BaseTheme.BUTTON_LINK");
		leftMainLayout.setRightMainClosableTabSheet(rightMainClosableTabSheet);
		leftMainLayout.setSizeFull();
		horizontalSplitPanel.setSplitPosition(100, UNITS_PIXELS);
		this.rightMainClosableTabSheet.setSizeFull();
	}
	public void setUserName(String userName){
		label_curren_user.setValue("当前用户:"+userName);
	}
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_top
		horizontalLayout_top = buildHorizontalLayout_top();
		mainLayout.addComponent(horizontalLayout_top);
		mainLayout
				.setComponentAlignment(horizontalLayout_top, new Alignment(6));
		
		// horizontalSplitPanel
		horizontalSplitPanel = buildHorizontalSplitPanel();
		mainLayout.addComponent(horizontalSplitPanel);
		mainLayout.setExpandRatio(horizontalSplitPanel, 1.0f);
		
		return mainLayout;
	}
	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_top() {
		// common part: create layout
		horizontalLayout_top = new HorizontalLayout();
		horizontalLayout_top.setImmediate(false);
		horizontalLayout_top.setWidth("300px");
		horizontalLayout_top.setHeight("-1px");
		horizontalLayout_top.setMargin(false);
		
		// label_curren_user
		label_curren_user = new Label();
		label_curren_user.setImmediate(false);
		label_curren_user.setWidth("-1px");
		label_curren_user.setHeight("-1px");
		label_curren_user.setValue("当前用户");
		horizontalLayout_top.addComponent(label_curren_user);
		
		// button_logout
		button_logout = new Button();
		button_logout.setStyleName("BaseTheme.BUTTON_LINK");
		button_logout.setCaption("注销");
		button_logout.setImmediate(true);
		button_logout.setWidth("-1px");
		button_logout.setHeight("-1px");
		horizontalLayout_top.addComponent(button_logout);
		
		return horizontalLayout_top;
	}
	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel() {
		// common part: create layout
		horizontalSplitPanel = new HorizontalSplitPanel();
		horizontalSplitPanel.setImmediate(false);
		horizontalSplitPanel.setWidth("100.0%");
		horizontalSplitPanel.setHeight("100.0%");
		horizontalSplitPanel.setMargin(false);
		
		// leftMainLayout
		leftMainLayout = new LeftMainLayout();
		leftMainLayout.setImmediate(false);
		leftMainLayout.setWidth("-1px");
		leftMainLayout.setHeight("-1px");
		horizontalSplitPanel.addComponent(leftMainLayout);
		
		// rightMainClosableTabSheet
		rightMainClosableTabSheet = new RightMainClosableTabSheet();
		rightMainClosableTabSheet.setImmediate(false);
		rightMainClosableTabSheet.setWidth("-1px");
		rightMainClosableTabSheet.setHeight("-1px");
		horizontalSplitPanel.addComponent(rightMainClosableTabSheet);
		
		return horizontalSplitPanel;
	}

}
