package com.hros.vaadin.myComponent;

import com.hros.user.domain.UserInfo;
import com.hros.vaadin.AppSession;
import com.hros.vaadin.SpringContextHelper;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class BaseForm extends CustomComponent {
	
	@AutoGenerated
	protected VerticalLayout mainLayout;
	
	public SpringContextHelper springHelp;
	
	public UserInfo user;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BaseForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	protected void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		this.setSizeFull();
	}
	
	@Override
	public void attach() {
		super.attach();
		springHelp = new SpringContextHelper(this.getApplication());
		user = new UserInfo();
	}
}
