package com.hros.staffstate.test;

import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.hros.customer.domain.Customer;
import com.hros.staffstate.dao.StaffStateDao;
import com.hros.staffstate.domain.Staff;
import com.hros.staffstate.domain.StaffState;
import com.vaadin.annotations.AutoGenerated;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations="/applicationContext.xml")
public class StaffStateTest {
	
	@Autowired
	private StaffStateDao staffStateDao;
	@Test
	public void test() {
		
	}
}
